name: Style & Linting

on: pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install linting tools
        run: pip install -r requirements_testing.txt

      - name: Run Ruff
        run: ruff check data sim models eval utils tests

      - name: Run Codespell
        run: codespell data sim models eval utils tests
